name: Hello World!
on:
  push:
  schedule:
    - cron: "*/6 * 28 * *"
jobs:
  hello-world:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - name: print-hello-world
        run: echo "Hello World!"
